# NSE tickers use suffix .NS in Yahoo Finance
# Example: RELIANCE.NS
UNIVERSE = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "LT.NS", "BHARTIARTL.NS",
    "AXISBANK.NS", "KOTAKBANK.NS", "ASIANPAINT.NS", "MARUTI.NS", "SUNPHARMA.NS",
    "HCLTECH.NS", "WIPRO.NS", "ULTRACEMCO.NS", "NTPC.NS", "TITAN.NS",
    "POWERGRID.NS", "M&M.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "ADANIENT.NS",
    "ADANIPORTS.NS", "ONGC.NS", "NESTLEIND.NS", "TATAMOTORS.NS", "COALINDIA.NS",
    "JSWSTEEL.NS", "TATASTEEL.NS", "DIVISLAB.NS", "HDFCLIFE.NS", "SBILIFE.NS",
    "DRREDDY.NS", "CIPLA.NS", "GRASIM.NS", "HEROMOTOCO.NS", "EICHERMOT.NS",
    "BRITANNIA.NS", "APOLLOHOSP.NS", "INDUSINDBK.NS", "TECHM.NS", "BPCL.NS",
    "SHRIRAMFIN.NS", "TATACONSUM.NS", "BAJAJ-AUTO.NS", "HINDALCO.NS", "UPL.NS"
]
